# Configuración para SQLite
driver=org.sqlite.JDBC
url=jdbc:sqlite:bd.sqlite3?date_string_format=yyyy-MM-dd&date_class=TEXT
# No necesitas usuario y contraseña para una base de datos SQLite
# username=bdprueba
# password=prueba
